name: CI - PactumJS Docker Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api-tests-with-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Start services with Docker Compose
        run: docker-compose up -d

      - name: Wait for services to be ready

        run: sleep 20

      - name: Run PactumJS API Tests
        run: npm test

      - name: Stop services
        if: always()
        run: docker-compose down

      - name: Publish Test Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          commit_message: 'docs: Deploy PactumJS test report'
        